manifest:

  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v3.6.0
      path: zephyr
      west-commands: scripts/west-commands.yml
      import:
        name-allowlist:
          - cmsis
          - picolibc

    - name: libcsp
      url: https://github.com/libcsp/libcsp.git
      revision: develop
      path: modules/lib/libcsp
