name: EOF newline

on:
  pull_request

jobs:
  linelint:
    runs-on: ubuntu-latest
    name: Check EOF newline

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Linelint
        uses: fernandrone/linelint@master
